
import type { Metadata } from "next";
import "@/app/globals.css";

import Header from "./components/shared/Header";
import Providers from '@/app/components/shared/providers';
import { Toaster } from "react-hot-toast";

export const metadata: Metadata = {
  title: "BAT",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <Header />
          {children}
          <Toaster position="top-center" />
        </Providers>
      </body>
    </html>
  );
}
